# Generated by Django 5.0.6 on 2024-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('long_description', models.TextField()),
                ('marketing_price', models.FloatField()),
                ('promotional_marketing_pricing', models.FloatField(default=0)),
                ('Type', models.CharField(choices=[('V', 'variação'), ('S', 'simples')], default='V', max_length=1)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m')),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
